### ISSUE TITLE
[Code] (1) - Avoid send unvalidated data to a web browser.

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#240]
Puede ocurrir un XSS de dos maneras:
a.	Cuando entra información a la aplicación a través de una fuente no segura, y tu sistema no tiene manera de validar la fuente.
b.	Cuando se manda contenido dinámico al usuario sin ser validado.
Contenido enviado al browser puede traer segmentos en forma de JavaScript, HTML of Flash y ser ejecutado por el navegador. Se puede extraer cookies, sesiones y hasta contraseñas. También es posible que la aplicación este mandando algún tipo de información de la base de datos como queries o sesiones.
Se recomienda Validar que información se está mandando a la variable ‘originUrl’, y que de cuál fuente podrá recibir información ’window.location’.
Source: var originUrl = urlResolve (window.location.href, true);
Path: public/build/dist/js/libs-d8c0538b.js

Archivo public/build/dist/js/libs-d8c0538b.js
Línea 35078

**Comment by codemoe** [comment]
@rodowi 

Ese código está tal cual en el core de angular JS. Sobre la variable que menciona el error se encuentra la siguiente nota:

// NOTE:  The usage of window and document instead of $window and $document here is
// deliberate.  This service depends on the specific behavior of anchor nodes created by the
// browser (resolving and parsing URLs) that is unlikely to be provided by mock objects and
// cause us to break tests.  In addition, when the browser resolves a URL for XHR, it
// doesn't know about mocked locations and resolves URLs to the real document - which is
// exactly the behavior needed here.  There is little value is mocking these out for this
// service.


Creo que este issue no es posible resolverlo como tal....
